from __future__ import annotations

from typing import Any

CATEGORIES = [
    "Resumen",
    "Tipo de cambio",
    "Inflación y reajustes",
    "Tasas y renta fija",
    "Actividad económica",
    "Mercado laboral",
    "Commodities",
    "Bolsa local",
    "Crédito y sistema financiero",
    "Riesgo país / externo",
    "Fiscal",
    "Expectativas",
]

# Nota: no se inventan códigos. Los códigos pendientes quedan explícitos como TODO.
INDICATORS: list[dict[str, Any]] = [
    # Tipo de cambio
    {"id":"usdclp","name":"Dólar observado USD/CLP","category":"Tipo de cambio","description":"Tipo de cambio nominal peso chileno por dólar observado.","source":"BCCh","code":"F073.TCO.PRE.Z.D","method":"sietews","frequency":"D","unit":"CLP por USD","primary_transform":"level","secondary_transformations":["var_dia","var_7d","var_30d","ma_50","ma_200"],"signal_rule":"usdclp","dashboard_priority":1,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Serie BDE/SieteWS dólar observado.","load_default":True},
    {"id":"euroclp","name":"Euro/CLP","category":"Tipo de cambio","description":"Tipo de cambio nominal peso chileno por euro.","source":"BCCh","code":"F072.CLP.EUR.N.O.D","method":"sietews","frequency":"D","unit":"CLP por EUR","primary_transform":"level","secondary_transformations":["var_dia","var_30d","ma_50"],"signal_rule":"generic_fx","dashboard_priority":9,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Pesos por unidad de moneda extranjera.","load_default":True},
    {"id":"mer","name":"Índice de Tipo de Cambio Multilateral","category":"Tipo de cambio","description":"Índice MER/TCM del Banco Central.","source":"BCCh","code":"F073.TCM.IND.199502.D","method":"sietews","frequency":"M","unit":"Índice","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"generic_index","dashboard_priority":10,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Índice 2 enero 1998 = 100.","load_default":True},
    {"id":"mer5","name":"MER-5","category":"Tipo de cambio","description":"Índice de tipo de cambio multilateral MER-5.","source":"BCCh","code":"F073.TM5.IND.199001.D","method":"sietews","frequency":"M","unit":"Índice","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"generic_index","dashboard_priority":11,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Serie complementaria de tipo de cambio multilateral.","load_default":True},
    {"id":"merx","name":"MER-X","category":"Tipo de cambio","description":"Índice de tipo de cambio multilateral MER-X.","source":"BCCh","code":"G073.TCMX.IND.199801.D","method":"sietews","frequency":"M","unit":"Índice","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"generic_index","dashboard_priority":12,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Serie complementaria de tipo de cambio multilateral.","load_default":True},

    # Inflación y reajustes
    {"id":"uf","name":"Unidad de Fomento","category":"Inflación y reajustes","description":"Valor diario de la UF en pesos.","source":"BCCh","code":"F073.UFF.PRE.Z.D","method":"sietews","frequency":"D","unit":"CLP","primary_transform":"level","secondary_transformations":["var_dia","var_30d"],"signal_rule":"generic_level","dashboard_priority":2,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Indicador de reajustabilidad diario.","load_default":True},
    {"id":"utm","name":"Unidad Tributaria Mensual","category":"Inflación y reajustes","description":"Valor mensual de la UTM.","source":"BCCh","code":"F073.UTR.PRE.Z.M","method":"sietews","frequency":"M","unit":"CLP","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"generic_level","dashboard_priority":13,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Indicador de reajustabilidad mensual.","load_default":True},
    {"id":"ipc_mensual","name":"IPC mensual","category":"Inflación y reajustes","description":"Variación mensual del IPC.","source":"BCCh","code":"F074.IPC.VAR.Z.EP23.C.M","method":"sietews","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["tendencia_6m"],"signal_rule":"ipc_mensual","dashboard_priority":3,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"IPC base 2023=100, variación mensual.","load_default":True},
    {"id":"ipc_anual","name":"IPC acumulado 12 meses","category":"Inflación y reajustes","description":"Inflación anual del IPC, variación 12 meses.","source":"BCCh","code":"F074.IPC.V12.Z.EP23.C.M","method":"sietews","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["tendencia_6m"],"signal_rule":"ipc","dashboard_priority":4,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Variación en 12 meses.","load_default":True},
    {"id":"ipc_indice","name":"Índice IPC general","category":"Inflación y reajustes","description":"Índice IPC general.","source":"BCCh","code":"F074.IPC.IND.Z.EP23.C.M","method":"sietews","frequency":"M","unit":"Índice","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"generic_index","dashboard_priority":14,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Índice IPC base 2023=100.","load_default":True},
    {"id":"tasa_real_ex_post","name":"Tasa real ex post aprox.","category":"Inflación y reajustes","description":"TPM menos inflación anual IPC.","source":"Derivado","code":None,"method":"derived","frequency":"M","unit":"pp","primary_transform":"spread","secondary_transformations":[],"signal_rule":"tasa_real","dashboard_priority":8,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Cálculo interno: TPM - IPC anual.","load_default":False},

    # Tasas y renta fija
    {"id":"tpm","name":"TPM efectiva","category":"Tasas y renta fija","description":"Tasa de política monetaria efectiva.","source":"BCCh","code":"F022.TPM.TIN.D001.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"tpm","dashboard_priority":5,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Serie diaria tipo escalón.","load_default":True},
    {"id":"tib","name":"Tasa interbancaria promedio","category":"Tasas y renta fija","description":"Tasa interbancaria promedio diaria.","source":"BCCh","code":"F022.TIB.TIP.D001.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["spread_tpm"],"signal_rule":"generic_rate","dashboard_priority":15,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Mercado interbancario.","load_default":True},
    {"id":"spc_90d","name":"SPC pesos 90 días","category":"Tasas y renta fija","description":"Tasa SPC pesos a 90 días.","source":"BCCh","code":"F022.SPC.TPR.D090.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"generic_rate","dashboard_priority":16,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva nominal corta.","load_default":True,"tenor_days":90},
    {"id":"spc_180d","name":"SPC pesos 180 días","category":"Tasas y renta fija","description":"Tasa SPC pesos a 180 días.","source":"BCCh","code":"F022.SPC.TPR.D180.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"generic_rate","dashboard_priority":17,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva nominal corta.","load_default":True,"tenor_days":180},
    {"id":"spc_360d","name":"SPC pesos 360 días","category":"Tasas y renta fija","description":"Tasa SPC pesos a 360 días.","source":"BCCh","code":"F022.SPC.TPR.D360.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"generic_rate","dashboard_priority":18,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva nominal corta.","load_default":True,"tenor_days":360},
    {"id":"bcp_2y","name":"BCP/BTP 2 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en pesos a 2 años.","source":"BCCh","code":"F022.BCLP.TIS.AN02.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva","dashboard_priority":19,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva nominal larga.","load_default":True,"tenor_days":730},
    {"id":"bcp_5y","name":"BCP/BTP 5 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en pesos a 5 años.","source":"BCCh","code":"F022.BCLP.TIS.AN05.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva","dashboard_priority":20,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva nominal larga.","load_default":True,"tenor_days":1825},
    {"id":"bcp_10y","name":"BCP/BTP 10 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en pesos a 10 años.","source":"BCCh","code":"F022.BCLP.TIS.AN10.NO.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva","dashboard_priority":21,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva nominal larga.","load_default":True,"tenor_days":3650},
    {"id":"bcu_1y","name":"Bonos UF 1 año","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en UF a 1 año (BCU/BTU).","source":"BCCh","code":"F022.BUF.TIS.AN01.UF.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":22,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva real UF de mercado secundario.","load_default":True,"tenor_days":365},
    {"id":"bcu_2y","name":"Bonos UF 2 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en UF a 2 años (BCU/BTU).","source":"BCCh","code":"F022.BUF.TIS.AN02.UF.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":22,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva real UF de mercado secundario.","load_default":True,"tenor_days":730},
    {"id":"bcu_5y","name":"Bonos UF 5 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en UF a 5 años (BCU/BTU).","source":"BCCh","code":"F022.BUF.TIS.AN05.UF.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":23,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva real UF de mercado secundario.","load_default":True,"tenor_days":1825},
    {"id":"bcu_10y","name":"Bonos UF 10 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en UF a 10 años (BCU/BTU).","source":"BCCh","code":"F022.BUF.TIS.AN10.UF.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":24,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva real UF de mercado secundario.","load_default":True,"tenor_days":3650},
    {"id":"bcu_20y","name":"Bonos UF 20 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en UF a 20 años (BCU/BTU).","source":"BCCh","code":"F022.BUF.TIS.AN20.UF.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":25,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva real UF de mercado secundario.","load_default":True,"tenor_days":7300},
    {"id":"bcu_30y","name":"Bonos UF 30 años","category":"Tasas y renta fija","description":"Tasa mercado secundario bonos en UF a 30 años (BCU/BTU).","source":"BCCh","code":"F022.BUF.TIS.AN30.UF.Z.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":26,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Curva real UF de mercado secundario.","load_default":True,"tenor_days":10950},
    {"id":"pendiente_nominal","name":"Pendiente curva nominal 10Y-2Y","category":"Tasas y renta fija","description":"Diferencia entre BCP/BTP 10Y y 2Y.","source":"Derivado","code":None,"method":"derived","frequency":"D","unit":"pp","primary_transform":"spread","secondary_transformations":["var_30d"],"signal_rule":"curva","dashboard_priority":25,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Cálculo interno: 10Y - 2Y.","load_default":False},
    {"id":"pendiente_uf","name":"Pendiente curva UF 10Y-2Y","category":"Tasas y renta fija","description":"Diferencia entre BCU 10Y y 2Y.","source":"Derivado","code":None,"method":"derived","frequency":"D","unit":"pp","primary_transform":"spread","secondary_transformations":["var_30d"],"signal_rule":"curva_uf","dashboard_priority":26,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Cálculo interno: 10Y - 2Y.","load_default":False},

    # Actividad económica
    {"id":"imacec_total","name":"IMACEC total","category":"Actividad económica","description":"Indicador mensual de actividad económica total.","source":"BCCh","code":"F032.IMC.IND.Z.Z.EP18.Z.Z.0.M","method":"sietews","frequency":"M","unit":"Índice 2018=100","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"imacec","dashboard_priority":6,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Volumen encadenado, referencia 2018.","load_default":True},
    {"id":"imacec_no_minero","name":"IMACEC no minero","category":"Actividad económica","description":"Indicador mensual de actividad económica no minera.","source":"BCCh","code":"F032.IMC.IND.Z.Z.EP18.N03.Z.0.M","method":"sietews","frequency":"M","unit":"Índice 2018=100","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"imacec","dashboard_priority":27,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Volumen encadenado, referencia 2018.","load_default":True},
    {"id":"imacec_mineria","name":"IMACEC minería","category":"Actividad económica","description":"Componente minería del IMACEC.","source":"BCCh","code":"F032.IMC.IND.Z.Z.EP18.03.Z.0.M","method":"sietews","frequency":"M","unit":"Índice 2018=100","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"imacec","dashboard_priority":28,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Volumen encadenado, referencia 2018.","load_default":True},
    {"id":"imacec_comercio","name":"IMACEC comercio","category":"Actividad económica","description":"Componente comercio del IMACEC.","source":"BCCh","code":"F032.IMC.IND.Z.Z.EP18.COM.Z.0.M","method":"sietews","frequency":"M","unit":"Índice 2018=100","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"imacec","dashboard_priority":29,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Volumen encadenado, referencia 2018.","load_default":True},
    {"id":"imacec_servicios","name":"IMACEC servicios","category":"Actividad económica","description":"Componente servicios del IMACEC.","source":"BCCh","code":"F032.IMC.IND.Z.Z.EP18.SERV.Z.0.M","method":"sietews","frequency":"M","unit":"Índice 2018=100","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"imacec","dashboard_priority":30,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Volumen encadenado, referencia 2018.","load_default":True},
    {"id":"pib_trimestral","name":"PIB trimestral","category":"Actividad económica","description":"Producto interno bruto trimestral, volumen encadenado.","source":"BCCh","code":"F032.PIB.FLU.R.CLP.EP18.Z.Z.0.T","method":"sietews","frequency":"T","unit":"MM CLP encadenado","primary_transform":"level","secondary_transformations":["var_trimestral","var_anual"],"signal_rule":"generic_activity","dashboard_priority":31,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Referencia 2018.","load_default":True},

    # Mercado laboral
    {"id":"desempleo","name":"Tasa de desocupación nacional","category":"Mercado laboral","description":"Tasa de desocupación nacional INE publicada en BDE.","source":"BCCh/INE","code":"F049.DES.TAS.INE9.10.M","method":"sietews","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["var_anual_pp"],"signal_rule":"desempleo","dashboard_priority":7,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Promedios móviles trimestrales, INE.","load_default":True},
    {"id":"ocupados","name":"Ocupados","category":"Mercado laboral","description":"Personas ocupadas, total.","source":"BCCh/INE","code":"F049.OCU.PMT.INE9.01.M","method":"sietews","frequency":"M","unit":"Miles de personas","primary_transform":"level","secondary_transformations":["var_anual"],"signal_rule":"labor_generic","dashboard_priority":32,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Promedios móviles trimestrales, INE.","load_default":True},
    {"id":"asalariados","name":"Asalariados","category":"Mercado laboral","description":"Ocupados asalariados.","source":"BCCh/INE","code":"F049.OCU.PMT.INE9.87.M","method":"sietews","frequency":"M","unit":"Miles de personas","primary_transform":"level","secondary_transformations":["var_anual"],"signal_rule":"labor_generic","dashboard_priority":33,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Categoría ocupacional asalariados.","load_default":True},
    {"id":"fuerza_trabajo","name":"Fuerza de trabajo","category":"Mercado laboral","description":"Fuerza de trabajo total.","source":"BCCh/INE","code":"F049.FTR.PMT.INE9.01.M","method":"sietews","frequency":"M","unit":"Miles de personas","primary_transform":"level","secondary_transformations":["var_anual"],"signal_rule":"labor_generic","dashboard_priority":34,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Promedios móviles trimestrales, INE.","load_default":True},
    {"id":"participacion_laboral","name":"Participación laboral","category":"Mercado laboral","description":"Tasa de participación laboral nacional.","source":"BCCh/INE","code":"TODO_BCCH_CODE","method":"pending","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["var_anual_pp"],"signal_rule":"labor_generic","dashboard_priority":35,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: confirmar código en catálogo BDE.","load_default":False},
    {"id":"informalidad_laboral","name":"Informalidad laboral","category":"Mercado laboral","description":"Tasa de ocupación informal.","source":"INE","code":"TODO_INE_CODE","method":"not_implemented","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["var_anual_pp"],"signal_rule":"labor_generic","dashboard_priority":36,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar fuente INE o confirmar disponibilidad BDE.","load_default":False},

    # Commodities
    {"id":"cobre","name":"Cobre refinado BML","category":"Commodities","description":"Precio del cobre refinado BML en dólares por libra.","source":"BCCh","code":"F019.PPB.PRE.100.D","method":"sietews","frequency":"D","unit":"USD/libra","primary_transform":"level","secondary_transformations":["var_30d","var_anual"],"signal_rule":"copper","dashboard_priority":37,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Precio diario.","load_default":True},
    {"id":"oro","name":"Oro","category":"Commodities","description":"Onza troy de oro en dólares.","source":"BCCh","code":"F019.PPB.PRE.44.D","method":"sietews","frequency":"D","unit":"USD/oz","primary_transform":"level","secondary_transformations":["var_30d","var_anual"],"signal_rule":"commodity_generic","dashboard_priority":38,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Precio diario.","load_default":True},
    {"id":"plata","name":"Plata","category":"Commodities","description":"Onza troy de plata en dólares.","source":"BCCh","code":"F019.PPB.PRE.45.D","method":"sietews","frequency":"D","unit":"USD/oz","primary_transform":"level","secondary_transformations":["var_30d","var_anual"],"signal_rule":"commodity_generic","dashboard_priority":39,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Precio diario.","load_default":True},

    # Bolsa local
    {"id":"ipsa","name":"IPSA","category":"Bolsa local","description":"Índice de Precio Selectivo de Acciones.","source":"BCCh/Bolsa","code":"F013.IBC.IND.N.7.LAC.CL.CLP.BLO.D","method":"sietews","frequency":"D","unit":"Índice","primary_transform":"level","secondary_transformations":["var_dia","var_mes","var_ytd","ma_50","ma_200"],"signal_rule":"ipsa","dashboard_priority":40,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Índice enero 2003=1000.","load_default":True},
    {"id":"ipsa_volumen","name":"Volumen transado IPSA","category":"Bolsa local","description":"Volumen transado del mercado local.","source":"Bolsa/CMF","code":"TODO_SOURCE","method":"not_implemented","frequency":"D","unit":"CLP","primary_transform":"level","secondary_transformations":[],"signal_rule":"none","dashboard_priority":41,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: confirmar fuente pública estable.","load_default":False},

    # Crédito y sistema financiero
    {"id":"tasa_comercial","name":"Tasas créditos comerciales","category":"Crédito y sistema financiero","description":"Tasas comerciales.","source":"CMF/BCCh","code":"TODO_SOURCE","method":"not_implemented","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["spread_tpm"],"signal_rule":"credito","dashboard_priority":42,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar módulo CMF o confirmar código BDE.","load_default":False},
    {"id":"tasa_consumo","name":"Tasas créditos consumo","category":"Crédito y sistema financiero","description":"Tasas de créditos de consumo.","source":"CMF/BCCh","code":"TODO_SOURCE","method":"not_implemented","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["spread_tpm"],"signal_rule":"credito","dashboard_priority":43,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar módulo CMF o confirmar código BDE.","load_default":False},
    {"id":"tasa_hipotecaria","name":"Tasas hipotecarias","category":"Crédito y sistema financiero","description":"Tasas hipotecarias.","source":"CMF/BCCh","code":"TODO_SOURCE","method":"not_implemented","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":["spread_tpm"],"signal_rule":"credito","dashboard_priority":44,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar módulo CMF o confirmar código BDE.","load_default":False},
    {"id":"tasa_interes_corriente","name":"Tasa de interés corriente","category":"Crédito y sistema financiero","description":"Tasa de interés corriente CMF.","source":"CMF","code":"TODO_CMF_CODE","method":"not_implemented","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"credito","dashboard_priority":45,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar cliente CMF.","load_default":False},
    {"id":"tasa_maxima_convencional","name":"Tasa máxima convencional","category":"Crédito y sistema financiero","description":"Tasa máxima convencional CMF.","source":"CMF","code":"TODO_CMF_CODE","method":"not_implemented","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"credito","dashboard_priority":46,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar cliente CMF.","load_default":False},

    # Riesgo país / externo
    {"id":"reservas_internacionales","name":"Reservas internacionales","category":"Riesgo país / externo","description":"Reservas internacionales en millones de dólares.","source":"BCCh","code":"F062.A5.STO.PF.USD.M","method":"sietews","frequency":"M","unit":"MM USD","primary_transform":"level","secondary_transformations":["var_mensual","var_anual"],"signal_rule":"reservas","dashboard_priority":47,"summary":True,"downloadable":True,"min_date":"2010-01-01","notes":"Posiciones denominadas en moneda extranjera del balance BCCh.","load_default":True},
    {"id":"us10y","name":"Treasury 10Y EE.UU.","category":"Riesgo país / externo","description":"Bono de gobierno de EE.UU. a 10 años.","source":"BCCh","code":"F019.TBG.TAS.10.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"external_rate","dashboard_priority":48,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Contexto externo.","load_default":True},
    {"id":"fed_funds_proxy","name":"Tasa política monetaria EE.UU.","category":"Riesgo país / externo","description":"Tasa de política monetaria de EE.UU.","source":"BCCh","code":"F019.TPM.TIN.10.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":["var_30d"],"signal_rule":"external_rate","dashboard_priority":49,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Proxy Fed Funds desde BDE.","load_default":True},
    {"id":"embi_chile","name":"EMBI/CDS Chile","category":"Riesgo país / externo","description":"Indicador de riesgo país Chile.","source":"Fuente externa","code":"TODO_SOURCE","method":"not_implemented","frequency":"D","unit":"pb","primary_transform":"level","secondary_transformations":[],"signal_rule":"risk_country","dashboard_priority":50,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: confirmar fuente pública estable.","load_default":False},

    # Fiscal
    {"id":"deuda_publica_pib","name":"Deuda pública bruta Gobierno Central / PIB","category":"Fiscal","description":"Deuda bruta del Gobierno Central como porcentaje del PIB.","source":"BCCh","code":"F051.D7.PPB.C.Z.Z.T","method":"sietews","frequency":"T","unit":"% PIB","primary_transform":"level","secondary_transformations":["var_anual_pp"],"signal_rule":"fiscal","dashboard_priority":51,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Finanzas públicas, deuda pública con relación al PIB.","load_default":True},
    {"id":"balance_fiscal","name":"Balance fiscal","category":"Fiscal","description":"Balance fiscal del Gobierno Central.","source":"DIPRES/BCCh","code":"TODO_SOURCE","method":"not_implemented","frequency":"M","unit":"% PIB / CLP","primary_transform":"level","secondary_transformations":[],"signal_rule":"fiscal","dashboard_priority":52,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar fuente fiscal.","load_default":False},
    {"id":"gasto_publico","name":"Gasto público","category":"Fiscal","description":"Gasto público.","source":"DIPRES/BCCh","code":"TODO_SOURCE","method":"not_implemented","frequency":"M","unit":"CLP","primary_transform":"level","secondary_transformations":[],"signal_rule":"fiscal","dashboard_priority":53,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"TODO: implementar fuente fiscal.","load_default":False},

    # Expectativas
    {"id":"eee_ipc_12m","name":"EEE inflación 11 meses","category":"Expectativas","description":"Expectativa de inflación en 11 meses, variación 12 meses.","source":"BCCh","code":"F089.IPC.V12.14.M","method":"sietews","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"expectativas","dashboard_priority":54,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Encuesta de Expectativas Económicas.","load_default":True},
    {"id":"eee_tpm_11m","name":"EEE TPM 11 meses","category":"Expectativas","description":"Expectativa TPM 11 meses.","source":"BCCh","code":"F089.TPM.TAS.14.M","method":"sietews","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"expectativas","dashboard_priority":55,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Encuesta de Expectativas Económicas.","load_default":True},
    {"id":"eee_tpm_23m","name":"EEE TPM 23 meses","category":"Expectativas","description":"Expectativa TPM 23 meses.","source":"BCCh","code":"F089.TPM.TAS.15.M","method":"sietews","frequency":"M","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"expectativas","dashboard_priority":56,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Encuesta de Expectativas Económicas.","load_default":True},
    {"id":"eof_ipc_12m","name":"EOF inflación 12 meses","category":"Expectativas","description":"Expectativa de inflación EOF próximos 12 meses.","source":"BCCh","code":"F089.EOF.VII.12MS.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"expectativas","dashboard_priority":57,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Encuesta de Operadores Financieros.","load_default":True},
    {"id":"eof_tpm_12m","name":"EOF TPM 12 meses","category":"Expectativas","description":"Expectativa de TPM EOF 12 meses.","source":"BCCh","code":"F089.EOF.TPM.12MS.D","method":"sietews","frequency":"D","unit":"%","primary_transform":"level","secondary_transformations":[],"signal_rule":"expectativas","dashboard_priority":58,"summary":False,"downloadable":True,"min_date":"2010-01-01","notes":"Encuesta de Operadores Financieros.","load_default":True},
]


def all_indicators() -> list[dict[str, Any]]:
    return sorted(INDICATORS, key=lambda x: (x.get("dashboard_priority", 999), x["id"]))


def indicator_map() -> dict[str, dict[str, Any]]:
    return {item["id"]: item for item in INDICATORS}


def indicators_dataframe():
    import pandas as pd
    return pd.DataFrame(all_indicators())


def implemented_indicators(load_default_only: bool = False) -> list[dict[str, Any]]:
    items = [i for i in all_indicators() if i.get("method") == "sietews" and i.get("code") and not str(i.get("code")).startswith("TODO")]
    if load_default_only:
        items = [i for i in items if i.get("load_default", True)]
    return items


def pending_indicators() -> list[dict[str, Any]]:
    return [i for i in all_indicators() if i.get("method") in {"pending", "not_implemented"} or str(i.get("code", "")).startswith("TODO")]
